### ISSUE TITLE
Keep default language locale in the URL

### ISSUE THREAD

**Issue by larsvankleef** [hozana/next-translate-routes#32]
Would it be possible to keep the `defaultLocale` string in the URL? By default, it looks like it adds redirects to prevent this. But I would like to keep this part in the URL.

For example 

```js
{
   i18n: {
     ​​locales: ['en', 'nl'],
     defaultLocale: ‘nl’,
   },
   translateRoutes: {
     redirectToDefaultLocale: true, // This should add a redirect for `example.com` to `example.com/nl`
     disableRedirectsToDefaultLocale: true, // This should disable the redirects added by default to remove the defaultlocale
   }
}
```

**Comment by cvolant** [comment]
Next consider that the default locale does not have a prefix, so that is the behavior implemented for now. You can remove the default locale: you will have the prefix for all urls, but of course you won't have the redirection from an url without prefix the the url with the `nl` prefix. It may be possible to add it yourself though, using redirects or middleware.

- Using redirect, I would try something like this but I will probably lead to looping redirects:
  ```
  {
    source: '/:path*',
    locale: false,
    destination: '/nl/:path*',
  }
  ```
- Using middleware: [see this reponse](https://github.com/vercel/next.js/discussions/18419)

If nothing works, we could think about adding this functionnality. Feel free to reopen this issue.
