### ISSUE TITLE
Add support for Next 13 `/app` directory

### ISSUE THREAD

**Issue by cvolant** [hozana/next-translate-routes#61]
Next 13 is now supported starting from next-translate-routes@1.9.2, but not the `/app` directory.

**Comment by pilleck** [comment]
Hey @cvolant are you already working on it? Maybe the Cineamo team can help you here?

**Comment by cvolant** [comment]
Hi @pilleck, no, not yet... And I don't know when I will be able to begin: that is not in our priorities for now. So if I had to estimate roughly when I will be able to, I would say in 1 year +/- 6 months.
So any help on this is welcome. I can provide advice, explanation of existing pieces of code, directions, review.
I didn't know Cineamo, so I visited the website: neat!

**Comment by ristomatti** [comment]
@cvolant I can definitely understand the pain! Thank you for publishing the new release regardless :pray:! We've been waitning for it as it removes the only blocker to upgrade to Next.js 13.5.

Thanks also for the indirect pointer to next-roots, will need to look it up!

Should this announcement be interpreted as the end of maintenance for page router as well? I'm merely asking so that we (and others in the same situation) know to start considering alternatives, such as [next-intl](https://github.com/amannn/next-intl). I have to say it doesn't look like a thrilling adventure as we're using next-i18next for the translations. :sweat_smile:

P.S. I'm still as amazed as I was 2.5 years ago how such an obvious feature is STILL not a built in feature in a framework like Next.js!

I was part of implementing i18n routing from scratch to a vanilla React SSR app w/ React Router 2.x several years in the past. I remember it was not insanely difficult but was ruprised to find myself pretty much clueless on how to aproach implementing it in Next.js. There's so much magic going on behind the scenes (and not even more so...). It was a huge relief to run across next-translate-routes after hours of googling at that point.
